# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'body_binary_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 10, 171, 84))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_file_pushButton = QtWidgets.QPushButton(self.widget)
        self.add_file_pushButton.setObjectName("add_file_pushButton")
        self.verticalLayout.addWidget(self.add_file_pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename_label = QtWidgets.QLabel(self.widget)
        self.filename_label.setObjectName("filename_label")
        self.horizontalLayout.addWidget(self.filename_label)
        self.add_file_pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.add_file_pushButton_2.setObjectName("add_file_pushButton_2")
        self.horizontalLayout.addWidget(self.add_file_pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_file_pushButton.setText(_translate("Form", "Select File"))
        self.filename_label.setText(_translate("Form", "TextLabel"))
        self.add_file_pushButton_2.setText(_translate("Form", "Select File"))
