# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 531)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.api_url_lineEdit = QtWidgets.QLineEdit(Form)
        self.api_url_lineEdit.setObjectName("api_url_lineEdit")
        self.horizontalLayout.addWidget(self.api_url_lineEdit)
        self.send_pushButton = QtWidgets.QPushButton(Form)
        self.send_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_pushButton.setObjectName("send_pushButton")
        self.horizontalLayout.addWidget(self.send_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.params_pushButton = QtWidgets.QPushButton(Form)
        self.params_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.params_pushButton.setObjectName("params_pushButton")
        self.horizontalLayout_2.addWidget(self.params_pushButton)
        self.headers_pushButton = QtWidgets.QPushButton(Form)
        self.headers_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.headers_pushButton.setObjectName("headers_pushButton")
        self.horizontalLayout_2.addWidget(self.headers_pushButton)
        self.body_pushButton = QtWidgets.QPushButton(Form)
        self.body_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.body_pushButton.setObjectName("body_pushButton")
        self.horizontalLayout_2.addWidget(self.body_pushButton)
        self.cookies_pushButton = QtWidgets.QPushButton(Form)
        self.cookies_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cookies_pushButton.setObjectName("cookies_pushButton")
        self.horizontalLayout_2.addWidget(self.cookies_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.api_stackedWidget = QtWidgets.QStackedWidget(Form)
        self.api_stackedWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.api_stackedWidget.setObjectName("api_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.api_stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.api_stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.api_stackedWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 4)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "GET"))
        self.comboBox.setItemText(1, _translate("Form", "POST"))
        self.comboBox.setItemText(2, _translate("Form", "PUT"))
        self.comboBox.setItemText(3, _translate("Form", "DELETE"))
        self.api_url_lineEdit.setPlaceholderText(_translate("Form", "请输入API地址"))
        self.send_pushButton.setText(_translate("Form", "Send"))
        self.params_pushButton.setText(_translate("Form", "Params"))
        self.headers_pushButton.setText(_translate("Form", "Headers"))
        self.body_pushButton.setText(_translate("Form", "Body"))
        self.cookies_pushButton.setText(_translate("Form", "Cookies"))
